server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root

# This is used to config server, so we can use application yaml data from GitHub server using this config
  config:
    import: configserver:http://localhost:8085

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-52003550.okta.com/oauth2/default
    audience: api://default